protocols = imap pop3 lmtp

listen = *

log_path = /var/log/dovecot.log
info_log_path = /var/log/dovecot.log

mail_location = maildir:/var/mail/vhosts/%d/%n/Maildir
mail_uid = vmail
mail_gid = vmail
mail_privileged_group = mail
first_valid_uid = 5000
last_valid_uid = 5000

namespace inbox {
  inbox = yes
  separator = /
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
}

passdb {
  driver = passwd-file
  args = scheme=SHA512-CRYPT username_format=%u /etc/dovecot/users
}

userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/vhosts/__DOMAIN__/catchall mail=maildir:/var/mail/vhosts/__DOMAIN__/catchall/Maildir
}

auth_mechanisms = plain login
disable_plaintext_auth = yes
auth_failure_delay = 5 secs

ssl = required
ssl_cert = </etc/letsencrypt/live/__HOSTNAME__/fullchain.pem
ssl_key  = </etc/letsencrypt/live/__HOSTNAME__/privkey.pem
ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = yes

service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

service auth {
  unix_listener auth-userdb {
    mode = 0600
    user = vmail
  }
}

protocol lmtp {
  mail_plugins = $mail_plugins
  postmaster_address = postmaster@__DOMAIN__
  hostname = __HOSTNAME__
}

protocol imap {
  mail_max_userip_connections = 20
}

protocol pop3 {
  mail_max_userip_connections = 20
  pop3_uidl_format = %08Xu%08Xv
}
